"""Reproducible simulation inputs, timing, and deterministic event lifecycle."""

from mobile_sensing.simulation.demand import (
    LocationWeight,
    OdWeight,
    generate_piecewise_poisson,
    iter_piecewise_poisson,
)
from mobile_sensing.simulation.kernel import (
    DEFAULT_MAX_EVENTS,
    DEFAULT_MAX_MICRO_ROUNDS,
    EVENT_KERNEL_VERSION,
    DecisionSnapshot,
    ExecutionLifecycleStatus,
    ExecutionOutcome,
    IdleActivityInterval,
    KernelCancelled,
    KernelDecisionAdapter,
    KernelResult,
    LifecycleEvent,
    PlannedAssignment,
    TaskLifecycleStatus,
    TaskOutcome,
    VehicleOutcome,
    run_event_kernel,
)
from mobile_sensing.simulation.dispatch import (
    DEFAULT_MAX_FEASIBLE_PAIRS,
    NEAREST_MATCHING_VERSION,
    PREDEFINED_DISPATCH_VERSION,
    EligibilityEngine,
    FeasiblePair,
    MatchingPairLimitExceeded,
    ScenarioDispatchError,
    SimulationDecisionAdapter,
)
from mobile_sensing.simulation.executor import (
    EXECUTOR_VERSION,
    GenericTaskExecutor,
    MaterializedExecution,
    MaterializedPosition,
    SharedRoutingCache,
    materialize_execution,
)
from mobile_sensing.simulation.operational import (
    DEPOT_RETURN_VERSION,
    RANDOM_CRUISE_VERSION,
    STATIONARY_IDLE_VERSION,
    OperationalDiagnostic,
    OperationalPolicyEngine,
)
from mobile_sensing.simulation.rng import SemanticRngStreams
from mobile_sensing.simulation.supply import build_generated_catalog, realize_availability
from mobile_sensing.simulation.storage import (
    SIMULATION_STORAGE_VERSION,
    SimulationArtifactReader,
    publish_simulation_results,
)
from mobile_sensing.simulation.timing import (
    StepTiming,
    TaskTiming,
    UnreachableTaskLeg,
    estimate_task_timing,
    task_with_release,
)

__all__ = [
    "DEFAULT_MAX_EVENTS",
    "DEFAULT_MAX_FEASIBLE_PAIRS",
    "DEFAULT_MAX_MICRO_ROUNDS",
    "EVENT_KERNEL_VERSION",
    "EXECUTOR_VERSION",
    "DecisionSnapshot",
    "DEPOT_RETURN_VERSION",
    "ExecutionLifecycleStatus",
    "ExecutionOutcome",
    "EligibilityEngine",
    "FeasiblePair",
    "GenericTaskExecutor",
    "IdleActivityInterval",
    "KernelCancelled",
    "KernelDecisionAdapter",
    "KernelResult",
    "LifecycleEvent",
    "LocationWeight",
    "MatchingPairLimitExceeded",
    "MaterializedExecution",
    "MaterializedPosition",
    "NEAREST_MATCHING_VERSION",
    "OperationalDiagnostic",
    "OperationalPolicyEngine",
    "OdWeight",
    "PlannedAssignment",
    "PREDEFINED_DISPATCH_VERSION",
    "RANDOM_CRUISE_VERSION",
    "ScenarioDispatchError",
    "SemanticRngStreams",
    "SIMULATION_STORAGE_VERSION",
    "SharedRoutingCache",
    "SimulationArtifactReader",
    "SimulationDecisionAdapter",
    "STATIONARY_IDLE_VERSION",
    "StepTiming",
    "TaskTiming",
    "TaskLifecycleStatus",
    "TaskOutcome",
    "UnreachableTaskLeg",
    "VehicleOutcome",
    "build_generated_catalog",
    "generate_piecewise_poisson",
    "estimate_task_timing",
    "iter_piecewise_poisson",
    "materialize_execution",
    "publish_simulation_results",
    "realize_availability",
    "run_event_kernel",
    "task_with_release",
]
