"""Deterministically generate the checked M09 OpenAPI and TypeScript contracts."""

from __future__ import annotations

import argparse
import json
import tempfile
from pathlib import Path
from typing import Any

from mobile_sensing.api import create_app
from mobile_sensing.contracts import canonical_json_text


def _typescript_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(_typescript_type(item) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(_typescript_type(item) for item in schema["oneOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    if "const" in schema:
        return json.dumps(schema["const"])
    kind = schema.get("type")
    if kind == "array":
        return f"ReadonlyArray<{_typescript_type(schema.get('items', {}))}>"
    if kind == "object":
        if "additionalProperties" in schema and isinstance(schema["additionalProperties"], dict):
            return f"Record<string, {_typescript_type(schema['additionalProperties'])}>"
        return "Record<string, unknown>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def _typescript(openapi: dict[str, Any]) -> str:
    lines = [
        "// Generated by python -m mobile_sensing.api.generate_contracts; do not edit.",
        "",
        f"export const API_VERSION = {json.dumps(openapi['info']['version'])} as const;",
        "",
    ]
    schemas = openapi.get("components", {}).get("schemas", {})
    for name in sorted(schemas):
        schema = schemas[name]
        if schema.get("type") != "object" or "properties" not in schema:
            lines.append(f"export type {name} = {_typescript_type(schema)};")
            lines.append("")
            continue
        required = set(schema.get("required", []))
        lines.append(f"export interface {name} {{")
        for field in sorted(schema["properties"]):
            suffix = "" if field in required else "?"
            lines.append(
                f"  {json.dumps(field)}{suffix}: {_typescript_type(schema['properties'][field])};"
            )
        lines.append("}")
        lines.append("")
    path_union = " | ".join(json.dumps(path) for path in sorted(openapi["paths"]))
    lines.append(f"export type ApiPath = {path_union};")
    lines.append("")
    return "\n".join(lines)


def generate(openapi_path: Path, typescript_path: Path) -> None:
    with tempfile.TemporaryDirectory() as artifact_root:
        schema = create_app(artifact_root).openapi()
    openapi_path.parent.mkdir(parents=True, exist_ok=True)
    typescript_path.parent.mkdir(parents=True, exist_ok=True)
    openapi_path.write_text(canonical_json_text(schema) + "\n", encoding="utf-8")
    typescript_path.write_text(_typescript(schema), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--openapi", type=Path, required=True)
    parser.add_argument("--typescript", type=Path, required=True)
    args = parser.parse_args()
    generate(args.openapi, args.typescript)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
